/** Curated options for profile form fields */

// ── Skills ──
// Grouped by domain relevance to BetterWorld's 15 UN SDG-aligned areas
export const SKILL_SUGGESTIONS = [
  // Community & Social
  "Community Organizing",
  "Volunteer Coordination",
  "Event Planning",
  "Public Speaking",
  "Conflict Resolution",
  "Mentoring",
  "Fundraising",
  "Grant Writing",
  "Nonprofit Management",
  "Social Work",

  // Environment & Sustainability
  "Environmental Science",
  "Renewable Energy",
  "Urban Farming",
  "Waste Management",
  "Water Conservation",
  "Wildlife Conservation",
  "Climate Science",
  "Sustainability Planning",

  // Education & Training
  "Teaching",
  "Tutoring",
  "Curriculum Design",
  "Youth Development",
  "Adult Literacy",
  "STEM Education",
  "Special Education",

  // Health & Wellness
  "Healthcare",
  "First Aid",
  "Mental Health Support",
  "Nutrition",
  "Public Health",
  "Elder Care",
  "Disability Support",

  // Technology
  "Software Engineering",
  "Web Development",
  "Mobile Development",
  "Data Analysis",
  "AI / Machine Learning",
  "Cybersecurity",
  "GIS / Mapping",
  "IT Support",
  "UX Design",
  "Graphic Design",

  // Professional
  "Project Management",
  "Research",
  "Technical Writing",
  "Translation",
  "Legal Aid",
  "Accounting",
  "Marketing",
  "Photography",
  "Videography",
  "Journalism",

  // Trades & Practical
  "Construction",
  "Electrical Work",
  "Plumbing",
  "Carpentry",
  "Landscaping",
  "Cooking",
  "Sewing",
  "Transportation",
  "Logistics",
  "Agriculture",
] as const;

// ── Countries ──
export const COUNTRIES = [
  "United States",
  "Canada",
  "United Kingdom",
  "Australia",
  "Germany",
  "France",
  "Japan",
  "South Korea",
  "India",
  "Brazil",
  "Mexico",
  "China",
  "Netherlands",
  "Sweden",
  "Norway",
  "Denmark",
  "Finland",
  "Switzerland",
  "Austria",
  "Belgium",
  "Ireland",
  "New Zealand",
  "Singapore",
  "Spain",
  "Italy",
  "Portugal",
  "Poland",
  "Czech Republic",
  "Argentina",
  "Chile",
  "Colombia",
  "Peru",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Ghana",
  "Egypt",
  "Morocco",
  "Israel",
  "Turkey",
  "United Arab Emirates",
  "Saudi Arabia",
  "Thailand",
  "Vietnam",
  "Philippines",
  "Indonesia",
  "Malaysia",
  "Taiwan",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Ukraine",
  "Romania",
  "Hungary",
  "Greece",
  "Croatia",
  "Iceland",
  "Estonia",
  "Latvia",
  "Lithuania",
  "Russia",
  "Costa Rica",
  "Panama",
  "Jamaica",
  "Trinidad and Tobago",
  "Dominican Republic",
  "Ecuador",
  "Bolivia",
  "Paraguay",
  "Uruguay",
  "Venezuela",
  "Guatemala",
  "Honduras",
  "El Salvador",
  "Nicaragua",
  "Cuba",
  "Ethiopia",
  "Tanzania",
  "Uganda",
  "Rwanda",
  "Senegal",
  "Cameroon",
  "Ivory Coast",
  "Mozambique",
  "Zimbabwe",
  "Zambia",
  "Botswana",
  "Namibia",
  "Tunisia",
  "Algeria",
  "Libya",
  "Jordan",
  "Lebanon",
  "Iraq",
  "Iran",
  "Afghanistan",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "Oman",
  "Myanmar",
  "Cambodia",
  "Laos",
  "Mongolia",
  "Fiji",
  "Papua New Guinea",
  "Luxembourg",
  "Malta",
  "Cyprus",
  "Slovenia",
  "Slovakia",
  "Serbia",
  "Bulgaria",
  "North Macedonia",
  "Albania",
  "Bosnia and Herzegovina",
  "Montenegro",
  "Moldova",
  "Georgia",
  "Armenia",
  "Azerbaijan",
  "Kazakhstan",
  "Uzbekistan",
] as const;

// ── Cities by country ──
// Major cities for countries where BetterWorld operates + common world cities
export const CITIES_BY_COUNTRY: Record<string, string[]> = {
  "United States": [
    "San Francisco",
    "New York",
    "Seattle",
    "Portland",
    "Chicago",
    "Denver",
    "Los Angeles",
    "Austin",
    "Boston",
    "Washington D.C.",
    "Philadelphia",
    "San Diego",
    "Dallas",
    "Houston",
    "Atlanta",
    "Miami",
    "Minneapolis",
    "Nashville",
    "Detroit",
    "Phoenix",
    "Charlotte",
    "Pittsburgh",
    "Columbus",
    "Indianapolis",
    "Salt Lake City",
    "Raleigh",
    "Richmond",
    "New Orleans",
    "Baltimore",
    "Milwaukee",
    "Kansas City",
    "St. Louis",
    "Tampa",
    "Orlando",
    "Sacramento",
    "Las Vegas",
    "Cleveland",
    "Cincinnati",
    "San Antonio",
    "Jacksonville",
    "Honolulu",
    "Anchorage",
  ],
  "Canada": [
    "Toronto",
    "Vancouver",
    "Montreal",
    "Calgary",
    "Ottawa",
    "Edmonton",
    "Winnipeg",
    "Quebec City",
    "Halifax",
    "Victoria",
  ],
  "United Kingdom": [
    "London",
    "Manchester",
    "Birmingham",
    "Edinburgh",
    "Glasgow",
    "Leeds",
    "Bristol",
    "Liverpool",
    "Cambridge",
    "Oxford",
    "Belfast",
    "Cardiff",
  ],
  "Australia": [
    "Sydney",
    "Melbourne",
    "Brisbane",
    "Perth",
    "Adelaide",
    "Canberra",
    "Gold Coast",
    "Hobart",
  ],
  "Germany": [
    "Berlin",
    "Munich",
    "Hamburg",
    "Frankfurt",
    "Cologne",
    "Stuttgart",
    "Düsseldorf",
    "Leipzig",
    "Dresden",
  ],
  "France": [
    "Paris",
    "Lyon",
    "Marseille",
    "Toulouse",
    "Nice",
    "Bordeaux",
    "Strasbourg",
    "Lille",
    "Nantes",
  ],
  "Japan": [
    "Tokyo",
    "Osaka",
    "Kyoto",
    "Yokohama",
    "Nagoya",
    "Sapporo",
    "Fukuoka",
    "Kobe",
  ],
  "South Korea": [
    "Seoul",
    "Busan",
    "Incheon",
    "Daegu",
    "Daejeon",
    "Gwangju",
    "Jeju",
  ],
  "India": [
    "Mumbai",
    "Delhi",
    "Bangalore",
    "Hyderabad",
    "Chennai",
    "Kolkata",
    "Pune",
    "Ahmedabad",
    "Jaipur",
  ],
  "Brazil": [
    "São Paulo",
    "Rio de Janeiro",
    "Brasília",
    "Curitiba",
    "Belo Horizonte",
    "Porto Alegre",
    "Salvador",
    "Recife",
    "Fortaleza",
  ],
  "Mexico": [
    "Mexico City",
    "Guadalajara",
    "Monterrey",
    "Puebla",
    "Cancún",
    "Tijuana",
    "Mérida",
    "Oaxaca",
  ],
  "China": [
    "Beijing",
    "Shanghai",
    "Shenzhen",
    "Guangzhou",
    "Chengdu",
    "Hangzhou",
    "Nanjing",
    "Wuhan",
    "Xi'an",
  ],
  "Netherlands": [
    "Amsterdam",
    "Rotterdam",
    "The Hague",
    "Utrecht",
    "Eindhoven",
    "Groningen",
  ],
  "Sweden": [
    "Stockholm",
    "Gothenburg",
    "Malmö",
    "Uppsala",
  ],
  "Norway": [
    "Oslo",
    "Bergen",
    "Trondheim",
    "Stavanger",
  ],
  "Denmark": [
    "Copenhagen",
    "Aarhus",
    "Odense",
    "Aalborg",
  ],
  "Finland": [
    "Helsinki",
    "Tampere",
    "Turku",
    "Oulu",
  ],
  "Switzerland": [
    "Zurich",
    "Geneva",
    "Basel",
    "Bern",
    "Lausanne",
  ],
  "Spain": [
    "Madrid",
    "Barcelona",
    "Valencia",
    "Seville",
    "Bilbao",
    "Málaga",
  ],
  "Italy": [
    "Rome",
    "Milan",
    "Florence",
    "Naples",
    "Turin",
    "Bologna",
    "Venice",
  ],
  "Portugal": [
    "Lisbon",
    "Porto",
    "Braga",
    "Coimbra",
  ],
  "New Zealand": [
    "Auckland",
    "Wellington",
    "Christchurch",
    "Hamilton",
    "Queenstown",
  ],
  "Singapore": [
    "Singapore",
  ],
  "Ireland": [
    "Dublin",
    "Cork",
    "Galway",
    "Limerick",
  ],
  "South Africa": [
    "Cape Town",
    "Johannesburg",
    "Durban",
    "Pretoria",
  ],
  "Nigeria": [
    "Lagos",
    "Abuja",
    "Port Harcourt",
    "Ibadan",
  ],
  "Kenya": [
    "Nairobi",
    "Mombasa",
    "Kisumu",
  ],
  "Israel": [
    "Tel Aviv",
    "Jerusalem",
    "Haifa",
  ],
  "Turkey": [
    "Istanbul",
    "Ankara",
    "Izmir",
    "Antalya",
  ],
  "United Arab Emirates": [
    "Dubai",
    "Abu Dhabi",
    "Sharjah",
  ],
  "Thailand": [
    "Bangkok",
    "Chiang Mai",
    "Phuket",
  ],
  "Vietnam": [
    "Ho Chi Minh City",
    "Hanoi",
    "Da Nang",
  ],
  "Philippines": [
    "Manila",
    "Cebu",
    "Davao",
  ],
  "Indonesia": [
    "Jakarta",
    "Bali",
    "Surabaya",
    "Bandung",
    "Yogyakarta",
  ],
  "Malaysia": [
    "Kuala Lumpur",
    "Penang",
    "Johor Bahru",
  ],
  "Taiwan": [
    "Taipei",
    "Kaohsiung",
    "Taichung",
    "Tainan",
  ],
  "Poland": [
    "Warsaw",
    "Krakow",
    "Wroclaw",
    "Gdansk",
    "Poznan",
  ],
  "Czech Republic": [
    "Prague",
    "Brno",
    "Ostrava",
  ],
  "Argentina": [
    "Buenos Aires",
    "Córdoba",
    "Rosario",
    "Mendoza",
  ],
  "Chile": [
    "Santiago",
    "Valparaíso",
    "Concepción",
  ],
  "Colombia": [
    "Bogotá",
    "Medellín",
    "Cali",
    "Cartagena",
    "Barranquilla",
  ],
  "Austria": [
    "Vienna",
    "Salzburg",
    "Graz",
    "Innsbruck",
  ],
  "Belgium": [
    "Brussels",
    "Antwerp",
    "Ghent",
    "Bruges",
  ],
  "Egypt": [
    "Cairo",
    "Alexandria",
    "Luxor",
  ],
  "Morocco": [
    "Casablanca",
    "Marrakech",
    "Rabat",
    "Fez",
  ],
  "Ghana": [
    "Accra",
    "Kumasi",
    "Tamale",
  ],
  "Costa Rica": [
    "San José",
  ],
  "Peru": [
    "Lima",
    "Cusco",
    "Arequipa",
  ],
  "Ukraine": [
    "Kyiv",
    "Lviv",
    "Odesa",
    "Kharkiv",
  ],
  "Romania": [
    "Bucharest",
    "Cluj-Napoca",
    "Timișoara",
  ],
  "Hungary": [
    "Budapest",
    "Debrecen",
  ],
  "Greece": [
    "Athens",
    "Thessaloniki",
  ],
  "Croatia": [
    "Zagreb",
    "Split",
    "Dubrovnik",
  ],
  "Iceland": [
    "Reykjavik",
  ],
  "Estonia": [
    "Tallinn",
    "Tartu",
  ],
  "Latvia": [
    "Riga",
  ],
  "Lithuania": [
    "Vilnius",
    "Kaunas",
  ],
  "Russia": [
    "Moscow",
    "Saint Petersburg",
    "Novosibirsk",
    "Kazan",
  ],
  "Saudi Arabia": [
    "Riyadh",
    "Jeddah",
    "Mecca",
  ],
  "Pakistan": [
    "Karachi",
    "Lahore",
    "Islamabad",
  ],
  "Bangladesh": [
    "Dhaka",
    "Chittagong",
  ],
  "Sri Lanka": [
    "Colombo",
    "Kandy",
  ],
  "Nepal": [
    "Kathmandu",
    "Pokhara",
  ],
  "Ethiopia": [
    "Addis Ababa",
  ],
  "Tanzania": [
    "Dar es Salaam",
    "Arusha",
    "Zanzibar City",
  ],
  "Uganda": [
    "Kampala",
  ],
  "Rwanda": [
    "Kigali",
  ],
  "Cambodia": [
    "Phnom Penh",
    "Siem Reap",
  ],
  "Georgia": [
    "Tbilisi",
    "Batumi",
  ],
  "Serbia": [
    "Belgrade",
    "Novi Sad",
  ],
};
